# Generated by Django 5.1.1 on 2024-09-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_group', '0002_module'),  # Adjust as per the last migration
        ('user_module', '0001_initial'),  # Adjust if there's a specific migration for the user module
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Truncate tables to clear existing data
            TRUNCATE TABLE user_module_usermodule CASCADE;
            TRUNCATE TABLE module_group_module CASCADE;
            TRUNCATE TABLE module_group_modulegroup CASCADE;

            -- Insert data into module_group_modulegroup table
            INSERT INTO module_group_modulegroup (id, group_name) VALUES
            (1, 'Training Management'),
            (2, 'User Management'),
            (3, 'Assessment Management'),
            (4, 'Tools');

            -- Insert data into module_group_module table with icons and URL patterns
            INSERT INTO module_group_module (id, module_name, module_url, icon, module_group_id) VALUES
            (1, 'Subject', 'subject:subject_list', 'fas fa-book', 1),
            (2, 'Category', 'category:category_list', 'fas fa-tags', 1),
            (3, 'Training Program', 'training_program:training_program_list', 'fas fa-calendar-alt', 1),
            (4, 'User', 'user:user_list', 'fas fa-user', 2),
            (5, 'Role', 'role:role_list', 'fas fa-briefcase', 2),
            (6, 'Module', 'module_group:module_list', 'fas fa-cogs', 2),
            (7, 'Module Group', 'module_group:module_group_list', 'fas fa-folder', 2),
            (8, 'User Module', 'user_module:user_module_list', 'fas fa-user-tag', 2),
            (9, 'Question', 'question:question_list', 'fas fa-user-tag', 3),
            (10, 'Tool', 'tools:exam_generator_view', 'fas fa-user-tag', 4);
            """
        )
    ]
