# Generated by Django 5.1.1 on 2024-09-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_group', '0003_alter_module_module_group'),
        ('module_group', '0004_insert_data'),
    ]

    operations = [
    ]
